catalog/urls.py
from django.urls import path

from . import views

app_name = 'catalog'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path(
        'category/<int:category_id>/',
        views.IndexView.as_view(),
        name='index_category'
    ),
    path(
        'maincategory/<int:main_category_id>/',
        views.CategoryView.as_view(),
        name='main_category'
    ),
    path('product/<int:pk>/', views.DetailView.as_view(), name='detail'),
]

market/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.staticfiles.urls import static

from .settings import ConfigClass


urlpatterns = [
    path('catalog/', include('catalog.urls')),
    path('admin/', admin.site.urls),
]

if ConfigClass.DEBUG:
    urlpatterns += static(
        ConfigClass.MEDIA_URL, document_root=ConfigClass.MEDIA_ROOT
    )

catalog/models.py
from django.db import models


class MainCategoryProduct(models.Model):
    name = models.CharField(max_length=200)
    priority = models.IntegerField(default=1000)

    def __str__(self):
        return self.name


class CategoryProduct(models.Model):
    name = models.CharField(max_length=200)
    main_category = models.ForeignKey(
        MainCategoryProduct, on_delete=models.CASCADE
    )
    # Вес категории. Чем ниже значение приортиета, тем выше вес.
    # Используется при рендеринге страницы для сортировки.
    # Поумолчанию 1000, что бы случайно забытые категории не вылезли в топ
    priority = models.IntegerField(default=1000)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    cost = models.DecimalField(max_digits=12, decimal_places=2, blank=True)
    rating = models.IntegerField()
    category = models.ForeignKey(CategoryProduct, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_parameters(self):
        return self.parameterproduct_set.all().order_by('priority')

    def get_main_parameters(self):
        ''' Параметры с приоритетом меньше 1000 '''
        return self.parameterproduct_set.filter(
            priority__lte=1000
        ).order_by('priority')

    def get_categorys_with_parameters(self):
        parameters = self.get_parameters()

        categorys_ids = (parametr.category_id for parametr in parameters)
        categorys_ids = list(set(categorys_ids))

        categorys_objects = CategoryParameterProduct.objects.filter(
            id__in=categorys_ids
        ).order_by('priority')

        categorys_with_parameters = []
        for category in categorys_objects:
            parameters_category = [
                parameter for parameter in parameters
                if parameter.category_id == category.id
            ]
            categorys_with_parameters.append({
                'category': category.name,
                'parameters': parameters_category,
            })

        return categorys_with_parameters

    def get_url_images(self):
        images = self.imagesproduct_set.all().order_by('priority')
        return [image.image_file.url for image in images]


def product_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/product_<id>/<filename>
    return 'product_{0}/{1}'.format(instance.product.id, filename)


class ImagesProduct(models.Model):
    image_file = models.ImageField(upload_to=product_directory_path)
    priority = models.IntegerField(default=1000)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class CategoryParameterProduct(models.Model):
    name = models.CharField(max_length=200)
    # Вес категории параметра. Чем ниже значение приортиета, тем выше вес.
    # Используется при рендеринге страницы для сортировки.
    # По-умолчанию 1000, что бы случайно забытые категории параметров
    # не вылезли в топ.
    priority = models.IntegerField(default=1000)

    def __str__(self):
        return self.name


class ParameterProduct(models.Model):
    CHOCES_TYPE = (
        ('str', 'str'),
        ('bool', 'bool'),
        ('int', 'int'),
        ('float', 'float'),
        ('dict', 'dict'),
        ('list', 'list'),
    )
    name = models.CharField(max_length=200)
    value = models.CharField(max_length=200)
    type = models.CharField(max_length=20, choices=CHOCES_TYPE, default='str')
    # Вес параметра. Чем ниже значение приортиета, тем выше вес.
    # Используется при рендеринге страницы для сортировки.
    # По-умолчанию 1000, что бы случайно забытые параметры не вылезли в топ.
    # А кроме того все параметры с приортетом меньше считаются основными.
    priority = models.IntegerField(default=1000)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    category = models.ForeignKey(
        CategoryParameterProduct, on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name

catalog/views.py
from django.views import generic

from .models import Product, MainCategoryProduct, CategoryProduct
from .helpers import get_categorys


class IndexView(generic.ListView):
    model = Product
    template_name = 'catalog/index.html'

    def get_queryset(self):
        if 'category_id' in self.kwargs:
            return Product.objects.filter(
                category_id__exact=self.kwargs['category_id']
            ).order_by('-rating', 'cost')[:5]
        return Product.objects.all().order_by('-rating', 'cost')[:5]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categorys'] = get_categorys()
        if 'category_id' in self.kwargs:
            context['current_category'] = CategoryProduct.objects.get(
                pk=self.kwargs['category_id']
            )
        return context


class CategoryView(generic.ListView):
    model = CategoryProduct
    template_name = 'catalog/main_category_detail.html'
    context_object_name = 'category_product_list'

    def get_queryset(self):
        if 'main_category_id' in self.kwargs:
            return CategoryProduct.objects.filter(
                main_category_id__exact=self.kwargs['main_category_id']
            )
        return CategoryProduct.objects.all().order_by('main_category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categorys'] = get_categorys()
        if 'main_category_id' in self.kwargs:
            context.update({
                'main_category_product': MainCategoryProduct.objects.get(
                    pk=self.kwargs['main_category_id']
                ),
            })
        return context


class DetailView(generic.DetailView):
    model = Product
    template_name = 'catalog/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'categorys_parameters': self.object.get_categorys_with_parameters(),
            'main_parameters': self.object.get_main_parameters(),
            'images_url': self.object.get_url_images(),
            'categorys': get_categorys(),
        })
        return context

catalog/templates/catalog/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
  {% block head %}
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

  <title>{% block title %}Крутой интернет магазин{% endblock %}</title>
  {% endblock %}
</head>
<body>
  <div class="container-fluid">
    <h1>Очень хороший интернет магазин</h1>
    <div class="row">
      <div class="col-8">
        <form>
          <div class="form-group">
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1">Маркет</span>
              </div>
              <input type="text" class="form-control" id="inputSearch" placeholder="введите поисковый запрос">
              <div class="input-group-append">
                <button type="submit" class="btn btn-primary">Найти</button>
              </div>
            </div>
          </div>
        </form>
      </div>
      <div class="col-4 d-flex">
        <div class="row">
          <div class="col">
            <a href="#" class="align-text-top">Город</a>
          </div>
          <div class="col">
            <a href="#" class="align-text-top">Отложенные</a>
          </div>
          <div class="col">
            <a href="#" class="align-text-top">Сравнение</a>
          </div>
          <div class="col">
            <a href="#" class="align-text-top">Корзина</a>
          </div>
        </div>
      </div>
    </div>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% for category in categorys %}
            {% if current_category %}
              {% if current_category.main_category.id == category.main.id %}
              <li class="nav-item dropdown active">
              {% else %}
              <li class="nav-item dropdown">
              {% endif %}
            {% else %}
              <li class="nav-item dropdown">
            {% endif %}
              <a class="nav-link dropdown-toggle" href="/main_category/{{ category.main }}/" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ category.main.name }}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% for sub_category in category.sub %}
                  {% if current_category %}
                    {% if current_category.id == sub_category.id %}
                      <a class="dropdown-item active" href="{% url 'catalog:index_category' sub_category.id %}">{{ sub_category.name }}</a>
                    {% else %}
                      <a class="dropdown-item" href="{% url 'catalog:index_category' sub_category.id %}">{{ sub_category.name }}</a>
                    {% endif %}
                  {% else %}
                    <a class="dropdown-item" href="{% url 'catalog:index_category' sub_category.id %}">{{ sub_category.name }}</a>
                  {% endif %}
                {% endfor %}
              </div>
            </li>
          {% endfor %}
        </ul>
      </div>
    </nav>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <div id="content" class="container-fluid">{% block content %}{% endblock %}</div>
    <div id="footer" class="container-fluid">
      {% block footer %}
      &copy; Copyright 2018 by D.Vologdin</a>.
      {% endblock %}
    </div>
  </div>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/detail.html
{% extends "catalog/base.html" %}

{% block content %}
{% if product %}
  <a href="{% url 'catalog:main_category' product.category.main_category_id %}">{{ product.category.main_category.name }}</a> - <a href="{% url 'catalog:index_category' product.category_id %}">{{ product.category.name }}</a>
  <h2>{{ product.name }} - {{ product.cost }} руб.</h2>
  <p>Рэйтинг пользователей: {{ product.rating }}</p>
  <div class="bd-example bd-example-tabs" role="tabpanel">
    <ul class="nav nav-tabs nav-fill" id="myTab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="description-tab" data-toggle="tab" href="#description" role="tab" aria-controls="home" aria-expanded="true">Описание</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="parameter-tab" data-toggle="tab" href="#parameter" role="tab" aria-controls="profile" aria-expanded="false">Характеристики</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="costs-tab" data-toggle="tab" href="#costs" role="tab" aria-controls="profile" aria-expanded="false">Цены</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="feedback-tab" data-toggle="tab" href="#feedback" role="tab" aria-controls="profile" aria-expanded="false">Отзывы {{ feedbacks|length }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="overview-tab" data-toggle="tab" href="#overview" role="tab" aria-controls="profile" aria-expanded="false">Обзоры</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="discussion-tab" data-toggle="tab" href="#discussion" role="tab" aria-controls="profile" aria-expanded="false">Обсуждения</a>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div role="tabpanel" class="tab-pane fade active show" id="description" aria-labelledby="description-tab" aria-expanded="true">
        <div class="row">
          <div class="col-1">
            {% if images_url %}
              {% for image_url in images_url %}
                <p><img src="{{ image_url }}" width="100" ></p>
              {% endfor %}
            {% endif %}
          </div>
          <div class="col-4">
            {% if images_url %}
              <p><img src="{{ images_url.0 }}"  width="350"></p>
            {% endif %}
          </div>
          <div class="col-7">
            <h3>Коротко о товаре</h3>
            <ul>
              {% for  parameter in main_parameters %}
                <li>{{ parameter.name }} - {{ parameter.value }}</li>
              {% endfor %}
            </ul>
            <p>{{ product.description }}</p>
          </div>
        </div>
      </div>
      <div class="tab-pane fade" id="parameter" role="tabpanel" aria-labelledby="parameter-tab" aria-expanded="false">
        <div class="row">
          <div class="col-4">
            {% if images_url %}
              <p><img src="{{ images_url.0 }}" width="350"></p>
            {% endif %}
          </div>
          <div class="col-8">
            <h2>Характеристики</h2>
            {% for category in categorys_parameters %}
              <h3>{{ category.category }}</h3>
              {% for parameter in category.parameters %}
                <li>{{ parameter.name }}: {{ parameter.value }}</li>
              {% endfor %}
            {% endfor %}
          </div>
        </div>
      </div>
      <div class="tab-pane fade" id="costs" role="tabpanel" aria-labelledby="costs-tab" aria-expanded="false">
        <p>Costs</p>
      </div>
      <div class="tab-pane fade" id="feedback" role="tabpanel" aria-labelledby="feedback-tab" aria-expanded="false">
        {% for feedback in feedbacks %}
          <h3>{{ feedback.user.name }}</h3>
          <p>Общая оценка: {{ feedback.rating }}</p>
          <p>{{ feedback.description }}</p>
          <hr>
        {% endfor %}
      </div>
      <div class="tab-pane fade" id="overview" role="tabpanel" aria-labelledby="overview-tab" aria-expanded="false">
        <p>overview</p>
      </div>
      <div class="tab-pane fade" id="discussion" role="tabpanel" aria-labelledby="discussion-tab" aria-expanded="false">
        <p>discussion</p>
      </div>
    </div>
  </div>
{% else %}
  <h2>Запрошеный товар не найден</h2>
{% endif %}

{% endblock content %}

catalog/templates/catalog/index.html
{% extends "catalog/base.html" %}

{% block content %}
{% if product_list %}
  {% if current_category %}
    <h1>{{ current_category.main_category.name }} - {{ current_category.name }}</h1>
  {% endif %}
  <div class="row">
  {% for product in product_list %}
    <div class="col-md-6 col-xl-4 d-flex align-items-stretch">
      <div class="card text-center" >
        <img src="{{ product.get_url_images.0 }}" width="100" align="middle" class="align-self-center">
        <div class="card-body">
          <h5 class="card-title">{{ product.name }} - {{ product.cost }} руб.</h5>
          <p class="card-text">Ретинг пользователей: {{ product.rating }}</p>
          <p class="card-text">{{ product.description }}</p>
          <a href="{% url 'catalog:detail' product.id %}" class="btn btn-primary">Посмотреть</a>
        </div>
      </div>
    </div>
  {% endfor %}
  </div>
{% else %}
    <p>No products are available.</p>
{% endif %}
{% endblock content %}

catalog/templates/catalog/main_category_detail.html
{% extends "catalog/base.html" %}

{% block content %}

<h1>{{ main_category_product.name }}</h1>
{% for category in category_product_list %}
  <li><a href="{% url 'catalog:index_category' category.id %}">{{ category.name }}</a></li>
{% endfor %}

{% endblock content %}